#!/bin/bash

python3 -m tests.tests_import 1>test.log
python3 -m tests.tests_datamapper 1>>test.log
python3 -m tests.tests_baseobjects 1>>test.log
python3 -m tests.tests_greedy 1>>test.log
python3 -m tests.tests_branchnbound 1>>test.log

#cat test.log
